### 获取用户信息

GET /ping HTTP/1.1

### 获取用户信息

GET /userInfo?name=robin
  &id=fds HTTP/1.1

### 获取用户信息

GET /user/info/test/robin HTTP/1.1

### 获取用户信息

POST /json HTTP/1.1
Content-Type: application/json

{
  "name": "robin",
  "id": "fds",
  "gender": 11
}

### 获取用户信息

GET /redirect HTTP/1.1
