### 注册用户

POST /users HTTP/1.1
Content-Type: application/json

{
  "username": "robin3",
  "password": "123456",
  "nickname": "robin2",
  "avatar": "https://avatars.githubusercontent.com/u/123456?v=4"
}
